### ISSUE TITLE
A maven build does not remove the created container's volume

### ISSUE THREAD

**Issue by gion86** [LorenzoBettini/it-docker-mongo-example#2]
Hello Lorenzo,

I'm using this project, exactly as it is, and I see that every time I run a maven build I get 2 more container volumes created in my disk (in /var/lib/docker/volumes). I actually realized this because my root partition was full!

I'm running this command:

`mvn -Pskip-testcontainers clean verify `

so no integration test, TestContainer should not be the guilty here.

Could be the maven docker plugin that doesn't remove the volumes created for test? 
Given this issue https://github.com/fabric8io/docker-maven-plugin/issues/763 I tried to add this execution to the pom.xml

``` 
<execution>
  <id>volume-cleanup</id>
  <phase>clean</phase>
  <goals><goal>volume-remove</goal></goals>
</execution>
```

But the result is:
```
[INFO] --- docker-maven-plugin:0.34.1:volume-remove (volume-cleanup) @ school ---
[INFO] DOCKER> No volume configuration found.
```
Not surprisingly....

So it maybe docker that created these 2 volumes, then I'm lost...

**Comment by LorenzoBettini** [comment]
When using docker some cleaning and garbage collection should be performed on the system now and then, by running its prune commands. I don't think there's something wrong in this example. Otherwise it might be a bug in docker or somewhere else.

**Comment by gion86** [comment]
Maybe this one is related: https://github.com/fabric8io/docker-maven-plugin/issues/552
Long issue still open...


I tried with 

`<autoRemove>true</autoRemove>`

option but the build fails with 

```
[INFO] --- docker-maven-plugin:0.38.1:stop (docker-stop) @ school ---
[INFO] DOCKER> [mongo:4.4.3]: Stop and removed container f515ce366df5 after 0 ms
[ERROR] DOCKER> (Unable to remove container [f515ce366df5] : {"message":"removal of container f515ce366df5 is already in progress"} (Conflict: 409))
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

Even with plugin version v0.38.1.

**Comment by LorenzoBettini** [comment]
As you see the container is stopped and removed so there's nothing much you can do besides that.
